name: munjiz
description: "منجز - سوق خدمات المنزل الذكي المتقدم"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Networking
  dio: ^5.3.2
  http: ^1.1.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Database
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  
  # UI Components
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.6.0
  
  # Navigation
  go_router: ^12.1.1
  
  # Authentication & Security
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  google_sign_in: ^6.1.5
  crypto: ^3.0.3
  
  # Location & Maps
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.1
  
  # Communication
  socket_io_client: ^2.0.3+1
  agora_rtc_engine: ^6.2.6
  
  # Payment
  stripe_payment: ^1.1.4
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.1.0
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  permission_handler: ^11.0.1
  url_launcher: ^6.1.14
  share_plus: ^7.2.1
  
  # AI & ML
  tflite_flutter: ^0.10.4
  
  # Notifications
  firebase_messaging: ^14.6.9
  flutter_local_notifications: ^16.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  
  # Testing
  mockito: ^5.4.2
  bloc_test: ^9.1.4
  
  # Linting
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/models/
  
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
